def get_dataset_specified_config(dataset):
    """Get dataset specific."""
    cfg = {
        "ImageNet": {
            "TRAINER.DCG.PROMPT_DEPTH": 12,
            "TRAINER.DCG.N_CTX": 4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.DCG.MIX":0,
            "TRAINER.W": 8.0,
             "DATALOADER.TRAIN_X.BATCH_SIZE":48
        },
        "ImageNetV2": {
            "TRAINER.DCG.PROMPT_DEPTH": 12,
            "TRAINER.DCG.N_CTX": 4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.DCG.MIX":0,
            "TRAINER.W": 8.0,
        },
         "ImageNetSketch": {
            "TRAINER.DCG.PROMPT_DEPTH": 12,
            "TRAINER.DCG.N_CTX": 4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.DCG.MIX":0,
            "TRAINER.W": 8.0,
        },
         "ImageNetR": {
            "TRAINER.DCG.PROMPT_DEPTH": 12,
            "TRAINER.DCG.N_CTX": 4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.DCG.MIX":0,
            "TRAINER.W": 8.0,
        },
         "ImageNetA": {
            "TRAINER.DCG.PROMPT_DEPTH": 12,
            "TRAINER.DCG.N_CTX": 4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.DCG.MIX":0,
            "TRAINER.W": 8.0,
        },
        "Caltech101": {
            "TRAINER.DCG.PROMPT_DEPTH": 10,
            "TRAINER.DCG.N_CTX": 1,
            "TRAINER.DCG.MIX":4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.W": 4.0,
            "OPTIM.MAX_EPOCH": 20,
            "TRAINER.DISTILL_W1": 1000.,
            "TRAINER.DISTILL_W2": 0.15,
            
        },
        "OxfordPets": {
            "TRAINER.DCG.PROMPT_DEPTH": 12,
            "TRAINER.DCG.N_CTX": 4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.DCG.MIX":1,
            "TRAINER.W": 0.1,
            "OPTIM.MAX_EPOCH": 20,
            "TRAINER.DISTILL_W1": 1000.,
            "TRAINER.DISTILL_W2": 0.15,
        },
        "StanfordCars": { 
            "TRAINER.DCG.PROMPT_DEPTH": 12,
            "TRAINER.DCG.N_CTX": 8,
            "TRAINER.DCG.N_CTX_V": 8,
            "TRAINER.DCG.MIX":1,
            "TRAINER.W": 4.0,
             "TRAINER.DISTILL_W1": 1.,
            "TRAINER.DISTILL_W2": 0.15,
        },
        "OxfordFlowers": {
            "TRAINER.DCG.PROMPT_DEPTH": 9,
            "TRAINER.DCG.N_CTX": 4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.DCG.MIX":1,
            "TRAINER.W": 8.0,
             "TRAINER.DISTILL_W1": 1000.,
            "TRAINER.DISTILL_W2": 0.15,
        },
        "Food101": {
            "TRAINER.DCG.PROMPT_DEPTH": 12,
            "TRAINER.DCG.N_CTX": 4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.DCG.MIX":1,
            "TRAINER.W": 0.5,
            "OPTIM.MAX_EPOCH": 20,
             "TRAINER.DISTILL_W1": 1000.,
            "TRAINER.DISTILL_W2": 0.15,
        },
        "FGVCAircraft": {
            "TRAINER.DCG.PROMPT_DEPTH": 12,
            "TRAINER.DCG.N_CTX": 4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.DCG.MIX":1,
            "TRAINER.W": 2.0,
            "OPTIM.MAX_EPOCH": 30,
             "TRAINER.DISTILL_W1": 10.,
            "TRAINER.DISTILL_W2": 0.15,
        },
        "SUN397": {
            "TRAINER.DCG.PROMPT_DEPTH": 12,
            "TRAINER.DCG.N_CTX": 4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.DCG.MIX":1,
            "TRAINER.W": 8.0,
             "TRAINER.DISTILL_W1": 0.01,
            "TRAINER.DISTILL_W2": 0.15,
        },
        "DescribableTextures": {
            "TRAINER.DCG.PROMPT_DEPTH": 12,
            "TRAINER.DCG.N_CTX": 4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.DCG.MIX":1,
            "TRAINER.W": 8.0,
            "OPTIM.MAX_EPOCH": 35,
            "TRAINER.DISTILL_W1": 1.,
            "TRAINER.DISTILL_W2": 0.15,
        },
        "EuroSAT": {
            "TRAINER.DCG.PROMPT_DEPTH": 8,
            "TRAINER.DCG.N_CTX": 4,
            "TRAINER.DCG.N_CTX_V": 4,
            "TRAINER.DCG.MIX":1,
            "TRAINER.W": 0.1,
            "OPTIM.MAX_EPOCH": 50,
            "TRAINER.DISTILL_W1": 0.1,
            "TRAINER.DISTILL_W2": 0.1,
        },
        "UCF101": {
            "TRAINER.DCG.PROMPT_DEPTH": 12,
            "TRAINER.DCG.N_CTX": 6,
            "TRAINER.DCG.N_CTX_V": 6,
            "TRAINER.DCG.MIX":1,
            "TRAINER.W": 2.0,
            "OPTIM.MAX_EPOCH": 30,
            "TRAINER.DISTILL_W1": 1000.,
            "TRAINER.DISTILL_W2": 0.15,
        },
    }.get(dataset, {})

    return " ".join([f"{k} {v}" for k, v in cfg.items()]).split(" ")
